version: '3'
services:
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./:/etc/nginx/conf.d
      - ./:/app
    networks:
      - server
  php: 
    build: 
      context: ./docker
      dockerfile: php.Dockerfile
    volumes:
      - ./:/app
    networks:
      - server
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    networks:
      - server
networks:
  server:
    driver: bridge
